---
# tasks file for roles/docker
- name: Install Docker
  become: yes
  apt:
    name: docker.io
    state: present

- name: Start Docker Service
  become: yes
  service:
    name: docker
    state: started

